# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LFModulesDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for LFModulesDemo
  pod 'LFStringLibs', :path => '../../Modules/NSString_Categorys/'
  
  
  # vendor Lib
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'YYModel'
  
  target 'LFModulesDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LFModulesDemoUITests' do
    # Pods for testing
  end

end
